### PR TITLE
V3notebooks

### PR DESCRIPTION
**Pull request by elisachisari**
Bring all notebooks up to date with v3

### CODE REVIEW

**Comment by damonge** [comment]
Note that, in this last commit, I realised there was a bug in the usage of mass translation in v2 (one should use `10**logM` instead of `M_use` [here](https://github.com/LSSTDESC/CCL/blob/71f8d34c48441248e4d1bf0619b1679fd773d824/pyccl/halos/hmfunc.py#L156)). Because of that, the last figure in this notebook has changed.

**Review by chrgeorgiou — COMMENTED** [review]
Everything worked for me except "Power spectrum example", "CalculatorMode" and "PerturbationTheoryPk" because I am lacking the necessary pacakges (classy, velocileptors).

**Comment by hsinfan1996** [comment]
Power spectrum example.ipynb: cell 3, `AttributeError: module 'pyccl' has no attribute 'core'`
Should be `print(ccl.cosmology.transfer_function_types.keys())`. I don't know why I did not get this error tomorrow.

**Comment by elisachisari** [comment]
@hsinfan1996 could you check the "Power spectrum..." case again? Now it runs for me after upgrading it to talk to the new emulator implementation

**Comment by elisachisari** [comment]
@hsinfan1996 "Calculator mode" works for me. Could you check again? Are you sure you are using the more up to date notebook from this branch?

**Comment by hsinfan1996** [comment]
The `Power spectrum example` notebook runs with no problem.

**Comment by hsinfan1996** [comment]
> @hsinfan1996 "Calculator mode" works for me. Could you check again? Are you sure you are using the more up to date notebook from this branch?

I found out I didn't checkout the v3notebooks branch. The other two NBs are good.

**Comment by elisachisari** [comment]
I double checked that "PerturbationTheory..." also works for me with the right dependencies installed. One thing that was important was to get fastpt from conda and not pip. The conda version is more up to date.

**Pull request merged**
