### PR TITLE
add binder environment.yml

### PR DESCRIPTION
**Pull request by cmbant**
With this files all the notebooks can be run online in binder by going to

http://mybinder.org/v2/gh/LSSTDESC/CCLX/master

(esp. useful for Windows users who can't easily run CCL locally yet). Could also add direct binder-online notebook links to the readme (just add "?filepath=..." at the end to link to specific file)

### CODE REVIEW

**Comment by damonge** [comment]
Pretty cool, thanks a lot @cmbant ! I'm happy to merge this, but I haven't been able to make it work yet. If I try to run the Halo-model-Pk notebook, it complains about not being able to find numpy or pyccl.

**Comment by cmbant** [comment]
You'd have to merge the PR first before it will work - you can try it running on my fork:
http://mybinder.org/v2/gh/cmbant/CCLX/master

**Comment by cmbant** [comment]
PS. I found CAMB was very slow on binder unless you force only one openmp thread - if any notebooks are doing anything heavy by openmp may want to do the same - e.g. for CAMB
```
if os.environ.get('BINDER_LAUNCH_HOST'):
    camb.config.ThreadNum=1
```

**Comment by damonge** [comment]
Great, thanks! I'm seeing that all the notebooks that depend on CLASS (or on unreleased versions of CCL) don't run. I don't think there's an easy way to get binder to install classy, right?

**Comment by cmbant** [comment]
You can add a docker file instead, eg. this is how I do the CAMB one so that it builds the latest git-commit version of CAMB, presumably you could git clone and build classy instead
https://github.com/cmbant/CAMB/blob/master/Dockerfile
 
(or just use CAMB instead.....)

**Comment by cmbant** [comment]
This now works with class by adding a postBuild for it

**Comment by damonge** [comment]
Amazing, thanks a lot!
Everything works for me except
a) Halo model stuff -> this is on us for not having made a release of the code in a while.
b) The MCMC notebook -> could we add emcee to the list of dependencies?

I've pinged @c-d-leonard (current CCL overlord) to greenlight this. I'm all for it.

**Comment by damonge** [comment]
Alright, green light. Thanks a lot @cmbant !

**Pull request merged**
