### PR TITLE
MG mu-Sigma examples with redshift and scale dependencies

### PR DESCRIPTION
**Pull request by mishakb**
This PR is to add two notebooks with examples to illustrate the use of the mu and Sigma modified gravity parameters that include redshift and scale dependencies. 

This is associated with the recently merged CCL PR for implementing scale dependent MG mu Sigma parameterization.

### CODE REVIEW

**Comment by mishakb** [comment]
@gqcristhian could you review this one please.

**Comment by gqcristhian** [comment]
Hello,

Sure!

Best regards
Cristhian Garcia

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by gqcristhian — APPROVED** [review]
If we want to split into two different example notebooks, seems fine to me.

**Comment by mishakb** [comment]
Yes, agreed!

**Comment by gqcristhian** [comment]
Great then!

**Pull request merged**
