### PR TITLE
added baryon models example notebook

### PR DESCRIPTION
**Pull request by nikosarcevic**
this was checked and blessed  by @elisachisari .

Can you check and bless it, @tilmantroester :much obliged:

### CODE REVIEW

**Comment by tilmantroester** [comment]
Just some very minor points:
- Mention that `pk_nonlin` is halofit
- Mention why `include_baryonic_effects` doesn't work for BACCOEmu
- Linear y-scale might be better
- The `^{-1}` in the k units is missing the `$$`
- The 3-space indent on both the `cosmo=cosmology_vanilla,` is really upsetting :P

**Comment by nikosarcevic** [comment]
> Just some very minor points:
> 
> * Mention that `pk_nonlin` is halofit -**-- OK**
> * Mention why `include_baryonic_effects` doesn't work for BACCOEmu -- **can you help with wording please?-**-
> * Linear y-scale might be better -**- OK will fix**
> * The `^{-1}` in the k units is missing the `$$` **-- will fix**
> * The 3-space indent on both the `cosmo=cosmology_vanilla,` is really upsetting :P **-- will fix**

**Comment by tilmantroester** [comment]
I think the issue was that `include_baryonic_effects` tries to apply the correction over the whole internal k and a range and bacco doesn't cover the same range but it'd be worth to check the details again.

**Comment by nikosarcevic** [comment]
> I think the issue was that `include_baryonic_effects` tries to apply the correction over the whole internal k and a range and bacco doesn't cover the same range but it'd be worth to check the details again.

Thank you, Tilman. I have implemented all the changes now.

**Comment by tilmantroester** [comment]
"(the issue was that include_baryonic_effects tries to apply the correction over the whole internal k and a range and bacco doesn't cover the same range)."
That's what I thought the issue was but I've not checked since I messed around with bacco sometime before the collaboration meeting. Did you check that this indeed still the case?

**Comment by nikosarcevic** [comment]
> "(the issue was that include_baryonic_effects tries to apply the correction over the whole internal k and a range and bacco doesn't cover the same range)." That's what I thought the issue was but I've not checked since I messed around with bacco sometime before the collaboration meeting. Did you check that this indeed still the case?

Yes I have. If a user specifies a scale factor array for example an_array = np.linspace(0.1, 1, 100), it will blow up as it only wants to calculate from 0.4. There should be a mention of it in the docstring as well.

**Comment by tilmantroester** [comment]
Ok, LGTM then!

**Pull request merged**
